---
title: "Healthy Infant Metabolome is Robust to Normal Variations in Gut Microbiome"
subtitle: "NERIC 2019"
author: "Quang Nguyen"
output:
  html_document:
    df_print: paged
header-includes:
  - \usepackage[labelfont=bf]{caption}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F, fig.align = "center", fig.pos = "H")
```

## Filtering, Transformation and Normalization 
We normalize taxonomic data to proportions by dividing individual counts by sample-specific sequencing depths. We first imputed all 0 values with a unit pseudocount and then transform the data using center log-ratio transformation implemented in the function `clr` from the package `compositions` in `R`. For untargeted metabolomic data, we transform the data into relative abundances similar to our taxonomic profiles, and then subsequently use the arcsine square root transform to ensure approximate homoscedasticity when applying linear models. For targeted metabolomic data sets, since the data is already in exact concentration format, we simply perform a log transformation, accounting for 0 values by imputing with the smallest non-zero concentration times 0.5. Models are fitted to the transformed data and the resulting predictions are back-transformed to preserve the coverage of predicted metabolite compositions.  

## Model Fitting and evaluation
We fit our machine learning models using the `caret` package in `R`. Scaling and Centering was performed on the predictor matrix prior to model fitting. We evaluate our models using 10-fold nested cross validation, where within each outer training set we nest a cross-validation procedure for parameter tuning which should prevent overfitting. For random forest models, we optimize the number of trees (`mtry`) per forest.   

## Simulation Strategy  

